appointment/urls.py
from django.urls import path
from .views import appointment,appointmentList,AppointmentDeleteView

urlpatterns = [
    path('', appointment,name='appointment'),
    path('appointmentList/', appointmentList,name='appointmentList'),
    path('appointmentDeleteView/<int:pk>', AppointmentDeleteView.as_view(),name='AppointmentDeleteView'),
]

doctors/urls.py
from django.urls import path
from .views import detailSpecialty,error404,about

urlpatterns = [
    path('detailSpecialty/<int:id>',detailSpecialty,name='detailSpecialty'),
    path('error404/',error404,name='erro404'),
    path('about/',about,name='about')
]

medicalAppointment/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from doctors.views import index



urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctors/', include('doctors.urls')),
    path('branchOffices/', include('branchOffices.urls')),
    path('appointment/', include('appointment.urls')),
    path('pruebas/', include('pruebas.urls')),
    path('users/', include('usersApp.urls')),
    path('controlPanel/', include('controlPanel.urls')),
    path('',index,name='index')
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointment/models.py
from django.conf import settings
from django.db import models
from django_userforeignkey.models.fields import UserForeignKey


from branchOffices.models import BranchOffices
from doctors.models import Specialty
from django.contrib.auth.models import User




class Appointment(models.Model):
    user = UserForeignKey(auto_user_add=True) 
    name = models.CharField('Nombre', max_length=100,null=True,blank=True)
    lastName = models.CharField('Apellido', max_length=100,null=True,blank=True)
    dni = models.IntegerField('DNI',null=True,blank=True)
    specialty = models.ForeignKey(Specialty, on_delete=models.CASCADE)
    date = models.DateField()
    branchOffices = models.ForeignKey(BranchOffices, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return str(self.name)


    class Meta:
        db_table = 'appointment'
        verbose_name = 'appointment'
        verbose_name_plural = 'appointments'

appointment/forms.py
from django import forms
from .models import Appointment
from django.contrib.auth.models import User
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker
from usersApp.models import Usuario


class formsAppointment(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'
        exclude = ('user',)
        labels = {
            'specialty':'Especialidad',
            'date':'Fecha',
            'branchOffices':'Seleccion la oficina'

        }

appointment/views.py
from locale import format

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView,DeleteView

from usersApp.models import Usuario

from .forms import formsAppointment
from .models import Appointment


@login_required(login_url='login')
def appointment(request):
    appointment = Appointment.objects.all()
    title = 'Citas Medicas'


    if request.method == 'POST':
        form = formsAppointment(request.POST)
        if form.is_valid():
            form.save()
        return redirect(to='appointmentList')
    else:
        form = formsAppointment()


    context = {
        'form':form,    
        'title':title,
    }

    return render(request, 'appointment/appointment.html',context)

def appointmentList(request):
    userActivate = request.user.id

    filterUser = Appointment.objects.filter(
        Q(user_id = userActivate)
    )


    context={
        'userActivate':userActivate,
        'filterUser':filterUser,

    }

    return render(request, 'appointment/appointmentDetail.html',context)



class AppointmentDeleteView(DeleteView):
    model = Appointment
    template_name = "appointment/appointmentDelete.html"
    success_url='/'

appointment/templates/appointment/appointentList.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{title}}{% endblock %}




{% block content %}




      
{% endblock %}

appointment/templates/appointment/appointment.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{title}}{% endblock %}




{% block content %}
<!-- tempus -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>


  
<!-- datapicker -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>


<!-- /tempus -->


<div class="jumbotron">
    <h1 class="display-4 text-center text-colored text-danger">{{title}}</h1>
</div>            


<div class="container">
    <div class="d-flex justify-content-center"  >
        <form class='w-50' method='POST' >
            {% csrf_token %}
                {{form | crispy}}
                <div class="d-flex justify-content-center">
                    <input class="btn btn-danger  " type='submit' value="Guardar">
                </div>
        </form>
    </div>
</div>

<script>
  let toDay = new Date();
  let toDayFull = toDay.getDate() + "/" + (toDay.getMonth() +1) + "/" + toDay.getFullYear();

  $(function () {
    $("#id_date").datetimepicker({
      format: 'd/m/Y',
      startDate:'+2021/12/12',
      lang:'es',
      timepicker:false,
      minDate:toDayFull,
      //maxDate:
      //minTime:
      //maxTime:

    });
  });
</script>

{% endblock %}

appointment/templates/appointment/appointmentDelete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{title}}{% endblock %}




{% block content %}
<div class="container d-flex justify-content-center align-content-center">
    <form method="post">{% csrf_token %}
        <p>Estas seguro de eliminar tu cita? "{{ object }}"?</p>
        <div class="d-flex justify-content-center">
            <input class="btn btn-success" type="submit" value="Confirmar">
            <a href="appointmentList" class="btn btn-danger ml-4">Cancelar</a>
    
        </div>
    </form>
</div>
{% endblock %}

appointment/templates/appointment/appointmentDetail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{title}}{% endblock %}




{% block content %}

{{formatDate}}

<div class="container">
    <table class="table">
        <thead>
          <tr class="text-center">
            <th scope="col">Usuario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Especialidad</th>
            <th scope="col">Fecha</th>
            <th scope="col">Sucursal</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
            {% for a in filterUser %}
                <tr class="text-center">
                    <td class='text-primary'>@{{a.user}}</td>
                    <td>{{a.name | upper}}</td>
                    <td>{{a.lastName | upper}}</td>
                    <td>{{a.specialty.name}}</td>
                    <td>{{a.date|date:"d/m/Y" }}</td>
                    <td>{{a.branchOffices.name}}</td>
                    <td><a href="{% url 'AppointmentDeleteView' a.id %}"><i class="fa fa-trash bg-danger p-2 text-white rounded"></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
    
</div>


{% endblock %}